import { Centre } from "./Centre";
import { ClassificationCas } from "./ClassificationCas";
import { Handicap } from "./Handicap";
import { Mendicite } from "./Mendicite";
import { Province } from "./Province";
import { Region } from "./Region";
import { Services } from "./Service";
import { SituationDeRue } from "./SituationDeRue";
import { SituationFamilial } from "./SituationFamilial";
import { SituationFinanciere } from "./SituationFinanciere";
import { SituationMedical } from "./SituationMedical";
import { Violance } from "./Violance";

export type Beneficiaire = {
  id?: number;
  nom?: string;
  prenom?: string;
  sexe?: string;
  groupeAge?: string;
  scolarite?: string;
  niveauScolaire?: string;
  sejour?: string;
  territoire?: string;
  situationSocial?: string;
  centre?: Centre;
  province?: Province;
  classificationCas?: ClassificationCas;
  handicap?: Handicap;
  mendicite?: Mendicite;
  services?: Services;
  situationDeRue?: SituationDeRue;
  situationFamilial?: SituationFamilial;
  situationFinanciere?: SituationFinanciere;
  situationMedical?: SituationMedical;
  violence?: Violance;
  region?: Region;
};
